linters-settings:
  govet:
    check-shadowing: true
linters:
  enable:
    - gofmt
    - goimports
    - revive
    - gosec
    - govet
    - ineffassign
    - typecheck
    - gomodguard
    - errcheck
    - staticcheck
    - unused
  fast: false
issues:
  fix: true
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 8m
  concurrency: 1
  issues-exit-code: 1
  tests: true
  skip-dirs-use-default: true
